---
- hosts: devserver
  become: yes
  ignore_errors: yes
    tasks:
      - name: Install package
        package:
          name: "{{ items}}"
          state: present  
       with_items:
        - unizip
        - wget
        - httpd                             
                                      
                      

